homeassistant:
  name: Hidden Ridge
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 360
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize

config:
discovery:
frontend:
history:
logbook:
recorder:
  db_url: postgres://@/hass
sun:
updater:

automation: !include_dir_merge_list automation
binary_sensor: !include ./configuration/binary_sensor.yaml
climate: !include ./configuration/climate.yaml
cover: !include ./configuration/cover.yaml
device_tracker: !include ./configuration/device_tracker.yaml
device_sun_light_trigger: !include ./configuration/presence_based_lighting.yaml
group: !include ./configuration/group.yaml
http: !include ./configuration/http.yaml
ifttt: !include ./configuration/ifttt.yaml
input_boolean: !include ./configuration/input_boolean.yaml
input_select: !include ./configuration/input_select.yaml
light: !include ./configuration/light.yaml
media_player: !include ./configuration/media_player.yaml
mqtt: !include ./configuration/mqtt.yaml
nest: !include ./configuration/nest.yaml
notify: !include ./configuration/notify.yaml
remote: !include ./configuration/remote.yaml
script: !include_dir_merge_named script
sensor: !include ./configuration/sensor.yaml
switch: !include ./configuration/switch.yaml
tts: !include ./configuration/tts.yaml
