## COMMUNICATION WITH SMARTTHINGS HUB AND ZWAVE RECEPTICAL
- platform: mqtt
  name: 'Christmas Lights'
  state_topic: "smartthings/Christmas Lights/switch"
  command_topic: "smartthings/Christmas Lights/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
## KEVO BRIDGE COMMAND AND STATUS
- platform: command_line
  scan_interval: 30
  switches:
    door_front:
      command_on: "python /home/hass/.homeassistant/kevo/lock-front.py"
      command_off: "python /home/hass/.homeassistant/kevo/unlock-front.py"
      command_state: "python /home/hass/.homeassistant/kevo/status-front.py"
      value_template: '{{ value == "Locked" }}'
    door_rear:
      command_on: "python /home/hass/.homeassistant/kevo/lock-rear.py"
      command_off: "python /home/hass/.homeassistant/kevo/unlock-rear.py"
      command_state: "python /home/hass/.homeassistant/kevo/status-rear.py"
      value_template: '{{ value == "Locked" }}'

## COLOR TEMP ADJUSTMENT OF HUE BULBS
- platform: flux
  lights:
    - light.livingroom
    - light.master_bedroom
    - light.cabinet_lights
  name: Fluxer
  start_time: '7:00'
  sunset_time: '21:30'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 255
  disable_brightness_adjust: True
  mode: xy
